### ISSUE TITLE
Remove Picture

### ISSUE THREAD

**Issue by dudutaulois** [Ethaan/instafeed-meteor#1]
Hey Ethaan,

I really like your implementation in Meteor. I'm trying to adapt your code and I need to add a "remove feed" function. 

How can I do this using instafeed? 

Best,

**Comment by Ethaan** [comment]
Well using instafeed i dont really know if there is something like "remove feed", but since you are just inserting some images inside a div container, you can use some jQuery over here.

```
Template.example.events({
 'click .feed' :function(event, target){
   var targetDivFeed = event.target;
   targetDivFeed.hide(); //http://api.jquery.com/hide/  OR
  targetDivFeed.remove() //https://api.jquery.com/remove/
 }
})
```

**Comment by dudutaulois** [comment]
Good idea.. this solution will work for me now.
I guess what I need is not an simple option. The client_ID is stored in (cookies?) and this will make the instafeed do not use the new credentials to add a different account.
